---
title: "NCEP example"
author: "JM Delgado"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Define request, download and convert from ncdf to data frame and save

### Define request
```{r, results='asis'}
library(scraping)
coor <- data.frame(lon=13.40,lat=52.52)
var <- c('temperature','relative humidity')
years <- c('2000','2001')

request <- def_request(coor,var,years)
knitr::kable(request)

```

### Download and convert from ncdf to data frame and save
```{r eval=FALSE}

get_nc(request)

nc2rds(request)

```


## Load rds data examples

### Load air temperature

```{r, results='asis'}
library(scraping)
library(dplyr)
library(lubridate)

var=lookup_var('temperature') %>% pull(varname)

myproj='/home/delgado/proj/scraping/'

df1=readRDS(paste0(myproj,var,'.rds'))

head(df1) %>% knitr::kable()

df1 %>%
    group_by(day=floor_date(time,"day")) %>%
    summarise(daily_max=max(value),daily_min=min(value),daily_mean=mean(value),var=first(var)) %>%  
    head() %>%
    knitr::kable()
```
